// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: api/proto/totalconnect.proto

package totalconnectv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vault messages
type UnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passphrase    string                 `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockRequest) Reset() {
	*x = UnlockRequest{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockRequest) ProtoMessage() {}

func (x *UnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockRequest.ProtoReflect.Descriptor instead.
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{0}
}

func (x *UnlockRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type UnlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockResponse) Reset() {
	*x = UnlockResponse{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockResponse) ProtoMessage() {}

func (x *UnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockResponse.ProtoReflect.Descriptor instead.
func (*UnlockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{1}
}

func (x *UnlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnlockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{2}
}

type LockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{3}
}

func (x *LockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCredentialRequest) Reset() {
	*x = AddCredentialRequest{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialRequest) ProtoMessage() {}

func (x *AddCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialRequest.ProtoReflect.Descriptor instead.
func (*AddCredentialRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{4}
}

func (x *AddCredentialRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AddCredentialRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AddCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCredentialResponse) Reset() {
	*x = AddCredentialResponse{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialResponse) ProtoMessage() {}

func (x *AddCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialResponse.ProtoReflect.Descriptor instead.
func (*AddCredentialResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{5}
}

func (x *AddCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddCredentialResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSSHKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyName       string                 `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSSHKeyRequest) Reset() {
	*x = GetSSHKeyRequest{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSSHKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSSHKeyRequest) ProtoMessage() {}

func (x *GetSSHKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSSHKeyRequest.ProtoReflect.Descriptor instead.
func (*GetSSHKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{6}
}

func (x *GetSSHKeyRequest) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

type GetSSHKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyName       string                 `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSSHKeyResponse) Reset() {
	*x = GetSSHKeyResponse{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSSHKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSSHKeyResponse) ProtoMessage() {}

func (x *GetSSHKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSSHKeyResponse.ProtoReflect.Descriptor instead.
func (*GetSSHKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{7}
}

func (x *GetSSHKeyResponse) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *GetSSHKeyResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GetSSHKeyResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

// File messages
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	ModTime       int64                  `protobuf:"varint,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{8}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{9}
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListFilesRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{10}
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type TransferFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferFileRequest) Reset() {
	*x = TransferFileRequest{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFileRequest) ProtoMessage() {}

func (x *TransferFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFileRequest.ProtoReflect.Descriptor instead.
func (*TransferFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{11}
}

func (x *TransferFileRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TransferFileRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type TransferFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferFileResponse) Reset() {
	*x = TransferFileResponse{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFileResponse) ProtoMessage() {}

func (x *TransferFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFileResponse.ProtoReflect.Descriptor instead.
func (*TransferFileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{12}
}

func (x *TransferFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferFileResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteFileRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SyncFilesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Source           string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination      string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	DeleteExtraneous bool                   `protobuf:"varint,3,opt,name=delete_extraneous,json=deleteExtraneous,proto3" json:"delete_extraneous,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncFilesRequest) Reset() {
	*x = SyncFilesRequest{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFilesRequest) ProtoMessage() {}

func (x *SyncFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFilesRequest.ProtoReflect.Descriptor instead.
func (*SyncFilesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{15}
}

func (x *SyncFilesRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SyncFilesRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SyncFilesRequest) GetDeleteExtraneous() bool {
	if x != nil {
		return x.DeleteExtraneous
	}
	return false
}

type SyncFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFilesResponse) Reset() {
	*x = SyncFilesResponse{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFilesResponse) ProtoMessage() {}

func (x *SyncFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFilesResponse.ProtoReflect.Descriptor instead.
func (*SyncFilesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{16}
}

func (x *SyncFilesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncFilesResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// Status messages
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{17}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{18}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRequest) Reset() {
	*x = GetProgressRequest{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRequest) ProtoMessage() {}

func (x *GetProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRequest.ProtoReflect.Descriptor instead.
func (*GetProgressRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{19}
}

func (x *GetProgressRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetProgressResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BytesTransferred int64                  `protobuf:"varint,2,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	TotalBytes       int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Percentage       float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetProgressResponse) Reset() {
	*x = GetProgressResponse{}
	mi := &file_api_proto_totalconnect_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressResponse) ProtoMessage() {}

func (x *GetProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_totalconnect_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressResponse.ProtoReflect.Descriptor instead.
func (*GetProgressResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_totalconnect_proto_rawDescGZIP(), []int{20}
}

func (x *GetProgressResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetProgressResponse) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *GetProgressResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *GetProgressResponse) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *GetProgressResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_proto_totalconnect_proto protoreflect.FileDescriptor

const file_api_proto_totalconnect_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/totalconnect.proto\x12\x0ftotalconnect.v1\"/\n" +
	"\rUnlockRequest\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x01 \x01(\tR\n" +
	"passphrase\"D\n" +
	"\x0eUnlockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\r\n" +
	"\vLockRequest\"(\n" +
	"\fLockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\">\n" +
	"\x14AddCredentialRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"A\n" +
	"\x15AddCredentialResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"-\n" +
	"\x10GetSSHKeyRequest\x12\x19\n" +
	"\bkey_name\x18\x01 \x01(\tR\akeyName\"n\n" +
	"\x11GetSSHKeyResponse\x12\x19\n" +
	"\bkey_name\x18\x01 \x01(\tR\akeyName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\"d\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x19\n" +
	"\bmod_time\x18\x04 \x01(\x03R\amodTime\"D\n" +
	"\x10ListFilesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"D\n" +
	"\x11ListFilesResponse\x12/\n" +
	"\x05files\x18\x01 \x03(\v2\x19.totalconnect.v1.FileInfoR\x05files\"O\n" +
	"\x13TransferFileRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\"I\n" +
	"\x14TransferFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"E\n" +
	"\x11DeleteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\".\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"y\n" +
	"\x10SyncFilesRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12+\n" +
	"\x11delete_extraneous\x18\x03 \x01(\bR\x10deleteExtraneous\"F\n" +
	"\x11SyncFilesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"\x0f\n" +
	"\rHealthRequest\"\xc6\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12F\n" +
	"\adetails\x18\x03 \x03(\v2,.totalconnect.v1.HealthResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x12GetProgressRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xb4\x01\n" +
	"\x13GetProgressResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12+\n" +
	"\x11bytes_transferred\x18\x02 \x01(\x03R\x10bytesTransferred\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2\xcb\x02\n" +
	"\x05Vault\x12I\n" +
	"\x06Unlock\x12\x1e.totalconnect.v1.UnlockRequest\x1a\x1f.totalconnect.v1.UnlockResponse\x12C\n" +
	"\x04Lock\x12\x1c.totalconnect.v1.LockRequest\x1a\x1d.totalconnect.v1.LockResponse\x12^\n" +
	"\rAddCredential\x12%.totalconnect.v1.AddCredentialRequest\x1a&.totalconnect.v1.AddCredentialResponse\x12R\n" +
	"\tGetSSHKey\x12!.totalconnect.v1.GetSSHKeyRequest\x1a\".totalconnect.v1.GetSSHKeyResponse2\xd0\x02\n" +
	"\x04File\x12M\n" +
	"\x04List\x12!.totalconnect.v1.ListFilesRequest\x1a\".totalconnect.v1.ListFilesResponse\x12W\n" +
	"\bTransfer\x12$.totalconnect.v1.TransferFileRequest\x1a%.totalconnect.v1.TransferFileResponse\x12Q\n" +
	"\x06Delete\x12\".totalconnect.v1.DeleteFileRequest\x1a#.totalconnect.v1.DeleteFileResponse\x12M\n" +
	"\x04Sync\x12!.totalconnect.v1.SyncFilesRequest\x1a\".totalconnect.v1.SyncFilesResponse2\xad\x01\n" +
	"\x06Status\x12I\n" +
	"\x06Health\x12\x1e.totalconnect.v1.HealthRequest\x1a\x1f.totalconnect.v1.HealthResponse\x12X\n" +
	"\vGetProgress\x12#.totalconnect.v1.GetProgressRequest\x1a$.totalconnect.v1.GetProgressResponseB/Z-github.com/totalconnect/api/v1;totalconnectv1b\x06proto3"

var (
	file_api_proto_totalconnect_proto_rawDescOnce sync.Once
	file_api_proto_totalconnect_proto_rawDescData []byte
)

func file_api_proto_totalconnect_proto_rawDescGZIP() []byte {
	file_api_proto_totalconnect_proto_rawDescOnce.Do(func() {
		file_api_proto_totalconnect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_totalconnect_proto_rawDesc), len(file_api_proto_totalconnect_proto_rawDesc)))
	})
	return file_api_proto_totalconnect_proto_rawDescData
}

var file_api_proto_totalconnect_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_proto_totalconnect_proto_goTypes = []any{
	(*UnlockRequest)(nil),         // 0: totalconnect.v1.UnlockRequest
	(*UnlockResponse)(nil),        // 1: totalconnect.v1.UnlockResponse
	(*LockRequest)(nil),           // 2: totalconnect.v1.LockRequest
	(*LockResponse)(nil),          // 3: totalconnect.v1.LockResponse
	(*AddCredentialRequest)(nil),  // 4: totalconnect.v1.AddCredentialRequest
	(*AddCredentialResponse)(nil), // 5: totalconnect.v1.AddCredentialResponse
	(*GetSSHKeyRequest)(nil),      // 6: totalconnect.v1.GetSSHKeyRequest
	(*GetSSHKeyResponse)(nil),     // 7: totalconnect.v1.GetSSHKeyResponse
	(*FileInfo)(nil),              // 8: totalconnect.v1.FileInfo
	(*ListFilesRequest)(nil),      // 9: totalconnect.v1.ListFilesRequest
	(*ListFilesResponse)(nil),     // 10: totalconnect.v1.ListFilesResponse
	(*TransferFileRequest)(nil),   // 11: totalconnect.v1.TransferFileRequest
	(*TransferFileResponse)(nil),  // 12: totalconnect.v1.TransferFileResponse
	(*DeleteFileRequest)(nil),     // 13: totalconnect.v1.DeleteFileRequest
	(*DeleteFileResponse)(nil),    // 14: totalconnect.v1.DeleteFileResponse
	(*SyncFilesRequest)(nil),      // 15: totalconnect.v1.SyncFilesRequest
	(*SyncFilesResponse)(nil),     // 16: totalconnect.v1.SyncFilesResponse
	(*HealthRequest)(nil),         // 17: totalconnect.v1.HealthRequest
	(*HealthResponse)(nil),        // 18: totalconnect.v1.HealthResponse
	(*GetProgressRequest)(nil),    // 19: totalconnect.v1.GetProgressRequest
	(*GetProgressResponse)(nil),   // 20: totalconnect.v1.GetProgressResponse
	nil,                           // 21: totalconnect.v1.HealthResponse.DetailsEntry
}
var file_api_proto_totalconnect_proto_depIdxs = []int32{
	8,  // 0: totalconnect.v1.ListFilesResponse.files:type_name -> totalconnect.v1.FileInfo
	21, // 1: totalconnect.v1.HealthResponse.details:type_name -> totalconnect.v1.HealthResponse.DetailsEntry
	0,  // 2: totalconnect.v1.Vault.Unlock:input_type -> totalconnect.v1.UnlockRequest
	2,  // 3: totalconnect.v1.Vault.Lock:input_type -> totalconnect.v1.LockRequest
	4,  // 4: totalconnect.v1.Vault.AddCredential:input_type -> totalconnect.v1.AddCredentialRequest
	6,  // 5: totalconnect.v1.Vault.GetSSHKey:input_type -> totalconnect.v1.GetSSHKeyRequest
	9,  // 6: totalconnect.v1.File.List:input_type -> totalconnect.v1.ListFilesRequest
	11, // 7: totalconnect.v1.File.Transfer:input_type -> totalconnect.v1.TransferFileRequest
	13, // 8: totalconnect.v1.File.Delete:input_type -> totalconnect.v1.DeleteFileRequest
	15, // 9: totalconnect.v1.File.Sync:input_type -> totalconnect.v1.SyncFilesRequest
	17, // 10: totalconnect.v1.Status.Health:input_type -> totalconnect.v1.HealthRequest
	19, // 11: totalconnect.v1.Status.GetProgress:input_type -> totalconnect.v1.GetProgressRequest
	1,  // 12: totalconnect.v1.Vault.Unlock:output_type -> totalconnect.v1.UnlockResponse
	3,  // 13: totalconnect.v1.Vault.Lock:output_type -> totalconnect.v1.LockResponse
	5,  // 14: totalconnect.v1.Vault.AddCredential:output_type -> totalconnect.v1.AddCredentialResponse
	7,  // 15: totalconnect.v1.Vault.GetSSHKey:output_type -> totalconnect.v1.GetSSHKeyResponse
	10, // 16: totalconnect.v1.File.List:output_type -> totalconnect.v1.ListFilesResponse
	12, // 17: totalconnect.v1.File.Transfer:output_type -> totalconnect.v1.TransferFileResponse
	14, // 18: totalconnect.v1.File.Delete:output_type -> totalconnect.v1.DeleteFileResponse
	16, // 19: totalconnect.v1.File.Sync:output_type -> totalconnect.v1.SyncFilesResponse
	18, // 20: totalconnect.v1.Status.Health:output_type -> totalconnect.v1.HealthResponse
	20, // 21: totalconnect.v1.Status.GetProgress:output_type -> totalconnect.v1.GetProgressResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_totalconnect_proto_init() }
func file_api_proto_totalconnect_proto_init() {
	if File_api_proto_totalconnect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_totalconnect_proto_rawDesc), len(file_api_proto_totalconnect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_proto_totalconnect_proto_goTypes,
		DependencyIndexes: file_api_proto_totalconnect_proto_depIdxs,
		MessageInfos:      file_api_proto_totalconnect_proto_msgTypes,
	}.Build()
	File_api_proto_totalconnect_proto = out.File
	file_api_proto_totalconnect_proto_goTypes = nil
	file_api_proto_totalconnect_proto_depIdxs = nil
}
